services:
  telegram-service:
    build: ./telegram-service
    restart: always
    depends_on:
      - wireguard-service
      - database-service
    env_file:
      - .env
    environment:
      # - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WIREGUARD_SERVICE_URL=http://wireguard-service:5001
      - DATABASE_SERVICE_URL=http://database-service:5002

  wireguard-service:
    build: ./wireguard-service
    restart: always
    privileged: true
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /root/wireguard-backup:/root/wireguard-backup
    ports:
      - "5001:5001"
      - "51820:51820/udp"  # Для проброса UDP-порта WireGuard
    environment:
      - SERVER_ENDPOINT=${SERVER_ENDPOINT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ADDRESS=${SERVER_ADDRESS}

  database-service:
    build: ./database-service
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wireguard
      - DB_USER=postgres
      - DB_PASS=${POSTGRES_PASSWORD}
      - WIREGUARD_SERVICE_URL=http://wireguard-service:5001
    ports:
      - "5002:5002"
    command: ["./wait-for-postgres.sh", "postgres", "python", "db_manager.py"]

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wireguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-adminpassword}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  cleanup-cron:
    image: alpine
    restart: always
    depends_on:
      - database-service
    command: >
      sh -c "apk add --no-cache curl &&
             echo '0 * * * * curl -X POST http://database-service:5002/cleanup_expired' > /etc/crontabs/root &&
             crond -f -d 8"

volumes:
  postgres-data:
  pgadmin-data: